### ISSUE TITLE
2024-05 petites améliorations et bogues

### ISSUE THREAD

**Issue by maxbellec** [TelesCoop/white-rabbit#8]
- [x] Réparer les emails de rappel
- [x] Alias : ne pas afficher les projets qui n'ont pas d'alias
- [x] dans le total par mois, il me semble qu'on a perdu le "total" et "total effectué" que j'utilise bcp
- [x] on a perdu le suivi des projets "client" avec total / prévu ?
- [x] meilleur affichage des nombres (ne pas afficher les zéros inutile, se limiter à un chiffre après la virgule)
- [x] une amélioration que j'aimerais faire depuis un moment c'est d'optimiser le chargement pour mettre du cache (30 minutes ?) sur la fonction qui va chercher les infos calendrier pour un employé
- [x] soit
    - [x] aller chercher les infos des calendriers toutes les 30 minutes, comme ça le cache est toujours hydraté (via commande django + cron)
    - [x] aller cherches les infos des calendriers en parallèle (ex)

**Comment by QuentinMadura** [comment]
Réparer les emails
